#!/usr/bin/env python3
"""Command-line interface for mity"""
import logging
from mitylib import commands

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG, format="%(message)s")
    args = commands.parse_args()
    try:
        args.func(args)
    except AttributeError:
        print("For help, try mity -h")
        pass
